{
 "title": "RavenDB",
 "description": "RavenDB monitoring template",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Databases",
    "query": "SHOW TAG VALUES ON \"telegraf\" FROM \"ravendb_databases\" WITH KEY = \"database_name\""
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Servers Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "public_server_url" ], "type": "tag" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\") \r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"ravendb_server\") |> last()",
     "select": [
      [
       { "params": [ "server_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Server Version" ], "type": "alias" }
      ],
      [
       { "params": [ "server_full_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Full Server Version" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_low_memory_severity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Low Mem" ], "type": "alias" }
      ],
      [
       { "params": [ "cluster_node_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Node State" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Certificate Expiration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"server_version\" or r[\"_field\"] == \"certificate_server_certificate_expiration_left_in_sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       {
        "params": [
         "certificate_server_certificate_expiration_left_in_sec"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "License Expiration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"license_expiration_left_in_sec\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "license_expiration_left_in_sec" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_process_usage\")\r\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "cpu_process_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Machine CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_machine_usage\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "cpu_machine_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Req/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\" or r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"network_requests_per_sec\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "network_requests_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_allocated_in_mb\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "memory_allocated_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dirty Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_total_dirty_in_mb\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "memory_total_dirty_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SWAP ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "Swap Usage - $tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_total_swap_usage_in_mb\" or r[\"_field\"] == \"memory_total_swap_size_in_mb\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "memory_total_swap_usage_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_in_sec\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime_in_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"network_tcp_active_connections\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "network_tcp_active_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_total_free_space_in_mb\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "disk_total_free_space_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of running backups",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "query": "from(bucket: \"influx\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ravendb_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"backup_current_number_of_running_backups\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       {
        "params": [
         "backup_current_number_of_running_backups"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Databases Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  }
 ]
}