{
 "title": "RavenDB - InfluxQL",
 "description": "RavenDB monitoring template",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Servers Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "public_server_url" ], "type": "tag" }
     ],
     "measurement": "ravendb_server",
     "query": "SELECT last(\"server_version\") AS \"Server Version\", last(\"server_full_version\") AS \"Full Server Version\", last(\"memory_low_memory_severity\") AS \"Low Mem\", last(\"cluster_node_state\") AS \"Node State\" FROM \"ravendb_server\" WHERE $timeFilter GROUP BY \"public_server_url\"",
     "select": [
      [
       { "params": [ "server_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Server Version" ], "type": "alias" }
      ],
      [
       { "params": [ "server_full_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Full Server Version" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_low_memory_severity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Low Mem" ], "type": "alias" }
      ],
      [
       { "params": [ "cluster_node_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Node State" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Certificate Expiration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "ravendb_server",
     "select": [
      [
       {
        "params": [
         "certificate_server_certificate_expiration_left_in_sec"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "License Expiration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "license_expiration_left_in_sec" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "cpu_process_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Machine CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "cpu_machine_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Req/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "network_requests_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "network_tcp_active_connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "memory_allocated_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dirty Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "memory_total_dirty_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SWAP ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "Swap Size - $tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "memory_total_swap_size_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Swap Usage - $tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "memory_total_swap_usage_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "disk_total_free_space_in_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       { "params": [ "uptime_in_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of running backups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_public_server_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "public_server_url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ravendb_server",
     "select": [
      [
       {
        "params": [
         "backup_current_number_of_running_backups"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Databases Overview",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "ravendb_databases",
     "select": [
      [
       { "params": [ "counts_alerts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "# Alerts" ], "type": "alias" }
      ],
      [
       { "params": [ "counts_documents" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "# Documents" ], "type": "alias" }
      ],
      [
       { "params": [ "counts_performance_hints" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "# Perf. Hints" ], "type": "alias" }
      ],
      [
       { "params": [ "indexes_errored_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "# Errored Indexes" ], "type": "alias" }
      ],
      [
       { "params": [ "indexes_errors_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "# Index Errors" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}